export const communities = [
  { id: 'all', name: 'All', icon: 'globe-outline', members: 52000, activity: 'very_high' },
  { id: 'calisthenics', name: 'Calisthenics', icon: 'body-outline', members: 18400, activity: 'high' },
  { id: 'gym', name: 'Gym', icon: 'barbell-outline', members: 31000, activity: 'very_high' },
  { id: 'football', name: 'Football', icon: 'football-outline', members: 24500, activity: 'high' },
  { id: 'tennis', name: 'Tennis', icon: 'tennisball-outline', members: 8900, activity: 'medium' },
  { id: 'running', name: 'Running', icon: 'walk-outline', members: 15200, activity: 'high' },
  { id: 'crossfit', name: 'CrossFit', icon: 'fitness-outline', members: 12100, activity: 'high' },
];

export const users = [
  {
    id: 'u1',
    name: 'Ahmed Al-Rashidi',
    username: 'ahmed_fit',
    type: 'athlete' as const,
    avatar: 'https://i.pravatar.cc/150?img=1',
    height: 178,
    weight: 82,
    age: 24,
    gender: 'male',
    interests: ['calisthenics', 'gym'],
    goal: 'build_muscle',
    rank: 'competitive_athlete',
    followers: 320,
    following: 145,
    bio: 'Calisthenics enthusiast. Chasing the muscle-up.',
    totalWorkouts: 68,
    totalVolume: 245000,
    bestStreak: 14,
    achievements: ['First Workout', '10 Day Streak', '100kg Bench', 'Community Leader'],
  },
  {
    id: 'u2',
    name: 'Sara Al-Mutairi',
    username: 'sara_runs',
    type: 'athlete' as const,
    avatar: 'https://i.pravatar.cc/150?img=5',
    height: 165,
    weight: 58,
    age: 27,
    gender: 'female',
    interests: ['running', 'crossfit'],
    goal: 'improve_fitness',
    rank: 'active_athlete',
    followers: 890,
    following: 234,
    bio: 'Marathon runner. CrossFit on weekends.',
    totalWorkouts: 42,
    totalVolume: 89000,
    bestStreak: 21,
    achievements: ['First Workout', '21 Day Streak', 'Half Marathon', 'Social Butterfly'],
  },
  {
    id: 'u3',
    name: 'Omar Hassan',
    username: 'omar_lifts',
    type: 'athlete' as const,
    avatar: 'https://i.pravatar.cc/150?img=3',
    height: 185,
    weight: 95,
    age: 30,
    gender: 'male',
    interests: ['gym'],
    goal: 'build_muscle',
    rank: 'elite_athlete',
    followers: 2100,
    following: 89,
    bio: 'Powerlifter. 200kg deadlift club.',
    totalWorkouts: 156,
    totalVolume: 890000,
    bestStreak: 30,
    achievements: ['First Workout', '30 Day Streak', '200kg Deadlift', 'Elite Status', 'Tournament Winner'],
  },
  {
    id: 'u4',
    name: 'Noura Al-Qahtani',
    username: 'noura_fit',
    type: 'athlete' as const,
    avatar: 'https://i.pravatar.cc/150?img=9',
    height: 170,
    weight: 63,
    age: 25,
    gender: 'female',
    interests: ['calisthenics', 'running'],
    goal: 'learn_skill',
    rank: 'active_athlete',
    followers: 560,
    following: 178,
    bio: 'Working on my handstand journey.',
    totalWorkouts: 35,
    totalVolume: 52000,
    bestStreak: 12,
    achievements: ['First Workout', '10 Day Streak', 'Handstand Hold'],
  },
];

export const coaches = [
  {
    id: 'c1',
    name: 'Khalid Mansour',
    specialization: ['calisthenics', 'crossfit'],
    rating: 4.8,
    reviewsCount: 94,
    pricePerSession: 150,
    currency: 'SAR',
    certifications: ['ACE Certified Personal Trainer', 'CrossFit Level 2', 'Calisthenics Movement Specialist'],
    bio: '10 years experience in calisthenics coaching. Helped over 200 athletes achieve their movement goals.',
    avatar: 'https://i.pravatar.cc/150?img=11',
    gym: 'g1',
    experience: 10,
    clients: 48,
    achievements: ['200+ Athletes Coached', 'National Calisthenics Judge', 'CrossFit Games Regional', 'Published Author'],
    beforeAfter: [
      { clientName: 'Mohammed K.', duration: '6 months', beforeWeight: 95, afterWeight: 78, goal: 'Weight Loss', beforeImage: 'https://picsum.photos/seed/before1/300/400', afterImage: 'https://picsum.photos/seed/after1/300/400', testimonial: 'Coach Khalid changed my life. Lost 17kg and gained so much confidence.' },
      { clientName: 'Ali S.', duration: '4 months', beforeWeight: 70, afterWeight: 75, goal: 'Muscle Gain', beforeImage: 'https://picsum.photos/seed/before2/300/400', afterImage: 'https://picsum.photos/seed/after2/300/400', testimonial: 'Gained 5kg of lean muscle with structured programming.' },
      { clientName: 'Fahad R.', duration: '3 months', beforeWeight: 88, afterWeight: 82, goal: 'Body Recomp', beforeImage: 'https://picsum.photos/seed/before3/300/400', afterImage: 'https://picsum.photos/seed/after3/300/400', testimonial: 'Dropped body fat while maintaining strength. Incredible coaching.' },
    ],
    courses: [
      { id: 'course1', name: 'Handstand Mastery', level: 'Beginner', price: 500, currency: 'SAR', duration: '8 weeks', enrolled: 34 },
      { id: 'course2', name: 'Muscle-Up Blueprint', level: 'Intermediate', price: 700, currency: 'SAR', duration: '12 weeks', enrolled: 22 },
    ],
    reviews: [
      { userId: 'u1', userName: 'Ahmed', rating: 5, text: 'Amazing coach! Helped me achieve my first muscle-up in 3 months.', date: '2026-02-10' },
      { userId: 'u4', userName: 'Noura', rating: 5, text: 'Very patient and knowledgeable. Highly recommend!', date: '2026-01-28' },
      { userId: 'u2', userName: 'Sara', rating: 4, text: 'Great training programs, very structured approach.', date: '2026-01-15' },
    ],
    socialLinks: { instagram: '@khalid_cali', youtube: 'KhalidMansourFitness' },
    posts: [
      { id: 'cp1', content: 'New client just hit their first muscle-up after 8 weeks of training! This is why I coach.', likes: 89, timestamp: '2026-02-19T10:00:00Z', type: 'text' as const },
      { id: 'cp2', content: 'Proper form on weighted pull-ups. Notice the full range of motion and controlled eccentric.', likes: 156, timestamp: '2026-02-17T14:00:00Z', type: 'image' as const, imageUrl: 'https://picsum.photos/seed/coachpost1/600/400' },
      { id: 'cp3', content: 'Registration open for my 8-week Handstand Mastery course. Limited spots available!', likes: 234, timestamp: '2026-02-15T09:00:00Z', type: 'text' as const },
    ],
  },
  {
    id: 'c2',
    name: 'Fatima Al-Dosari',
    specialization: ['gym', 'crossfit'],
    rating: 4.9,
    reviewsCount: 156,
    pricePerSession: 200,
    currency: 'SAR',
    certifications: ['NASM Certified Personal Trainer', 'Precision Nutrition Level 1', 'CrossFit Level 1'],
    bio: 'Certified personal trainer specializing in body transformation. 8 years of experience helping women achieve their fitness goals.',
    avatar: 'https://i.pravatar.cc/150?img=16',
    gym: 'g2',
    experience: 8,
    clients: 65,
    achievements: ['500+ Transformations', 'Nutrition Expert', 'Women\'s Fitness Ambassador', 'TEDx Speaker'],
    beforeAfter: [
      { clientName: 'Maha T.', duration: '5 months', beforeWeight: 80, afterWeight: 65, goal: 'Weight Loss', beforeImage: 'https://picsum.photos/seed/before4/300/400', afterImage: 'https://picsum.photos/seed/after4/300/400', testimonial: 'Lost 15kg and feel amazing. Coach Fatima is incredible.' },
      { clientName: 'Reem A.', duration: '6 months', beforeWeight: 55, afterWeight: 60, goal: 'Muscle Gain', beforeImage: 'https://picsum.photos/seed/before5/300/400', afterImage: 'https://picsum.photos/seed/after5/300/400', testimonial: 'Finally gained the lean muscle I wanted. Best decision ever.' },
    ],
    courses: [
      { id: 'course3', name: 'Total Body Transformation', level: 'All Levels', price: 800, currency: 'SAR', duration: '16 weeks', enrolled: 56 },
    ],
    reviews: [
      { userId: 'u2', userName: 'Sara', rating: 5, text: 'Life-changing program. Lost 12kg in 5 months!', date: '2026-02-05' },
      { userId: 'u4', userName: 'Noura', rating: 5, text: 'Best trainer I have ever worked with.', date: '2026-01-20' },
    ],
    socialLinks: { instagram: '@fatima_fitness', youtube: 'FatimaDosariFit' },
    posts: [
      { id: 'cp4', content: 'Meal prep Sunday! Here\'s a balanced plate: 40g protein, 50g carbs, 15g healthy fats.', likes: 312, timestamp: '2026-02-18T08:00:00Z', type: 'image' as const, imageUrl: 'https://picsum.photos/seed/coachpost2/600/400' },
      { id: 'cp5', content: 'Reminder: Progress is not always linear. Trust the process and stay consistent.', likes: 198, timestamp: '2026-02-16T11:00:00Z', type: 'text' as const },
    ],
  },
  {
    id: 'c3',
    name: 'Tariq Al-Harbi',
    specialization: ['football', 'running'],
    rating: 4.7,
    reviewsCount: 72,
    pricePerSession: 120,
    currency: 'SAR',
    certifications: ['UEFA B License', 'Sports Science BSc', 'Running Coach Certification'],
    bio: 'Former professional footballer. Now coaching the next generation of athletes. 15 years experience.',
    avatar: 'https://i.pravatar.cc/150?img=12',
    gym: 'g1',
    experience: 15,
    clients: 30,
    achievements: ['Pro Football Career', 'UEFA Licensed', '300+ Youth Athletes', 'Marathon Finisher'],
    beforeAfter: [
      { clientName: 'Yousef M.', duration: '4 months', beforeWeight: 75, afterWeight: 72, goal: 'Speed Improvement', beforeImage: 'https://picsum.photos/seed/before6/300/400', afterImage: 'https://picsum.photos/seed/after6/300/400', testimonial: 'Improved my 100m sprint by 0.5 seconds. Coach Tariq knows football.' },
    ],
    courses: [
      { id: 'course4', name: 'Football Skills Camp', level: 'Beginner', price: 400, currency: 'SAR', duration: '6 weeks', enrolled: 18 },
    ],
    reviews: [
      { userId: 'u1', userName: 'Ahmed', rating: 5, text: 'Incredible football knowledge.', date: '2026-02-12' },
    ],
    socialLinks: { instagram: '@tariq_football' },
    posts: [
      { id: 'cp6', content: 'Morning agility drills with my U-17 squad. Building the next generation!', likes: 67, timestamp: '2026-02-19T07:00:00Z', type: 'image' as const, imageUrl: 'https://picsum.photos/seed/coachpost3/600/400' },
    ],
  },
];

export const gyms = [
  {
    id: 'g1',
    name: 'Iron Peak Gym',
    rating: 4.6,
    distance: '1.2 km',
    address: 'King Fahad Road, Riyadh',
    lat: 24.7136,
    lng: 46.6753,
    types: ['bodybuilding', 'crossfit'],
    facilities: ['Sauna', 'Parking', 'Showers', 'Cafe', 'Boxing Ring', 'Swimming Pool'],
    subscriptions: [
      { name: 'Monthly', price: 200, currency: 'SAR' },
      { name: 'Quarterly', price: 500, currency: 'SAR' },
      { name: 'Yearly', price: 1800, currency: 'SAR' },
    ],
    workingHours: '6:00 AM - 12:00 AM',
    coaches: ['c1', 'c3'],
    description: 'Premium fitness facility with state-of-the-art equipment, dedicated zones for crossfit, bodybuilding, and calisthenics training.',
    phone: '+966 11 234 5678',
    memberCount: 450,
    events: [
      { id: 'ge1', name: 'Deadlift Challenge', date: '2026-03-01', time: '6:00 PM', description: 'Max out your deadlift. Prizes for top 3.', attendees: 32 },
      { id: 'ge2', name: 'CrossFit WOD Night', date: '2026-03-08', time: '7:00 PM', description: 'Weekly community WOD. All levels welcome.', attendees: 45 },
    ],
    posts: [
      { id: 'gp1', content: 'New equipment alert! Just installed 4 new power racks and an Olympic lifting platform.', likes: 178, timestamp: '2026-02-19T12:00:00Z', type: 'text' as const },
      { id: 'gp2', content: 'Iron Peak CrossFit WOD of the day: 21-15-9 Thrusters + Pull Ups. Post your time below!', likes: 94, timestamp: '2026-02-18T06:30:00Z', type: 'text' as const },
      { id: 'gp3', content: 'Our members crushing it at the early morning session. Nothing beats 5AM gains!', likes: 256, timestamp: '2026-02-17T06:00:00Z', type: 'image' as const, imageUrl: 'https://picsum.photos/seed/gympost1/600/400' },
    ],
    schedule: [
      { day: 'Sunday', classes: ['CrossFit 6AM', 'Bodybuilding 8AM', 'Boxing 5PM', 'Open Gym 7PM'] },
      { day: 'Monday', classes: ['CrossFit 6AM', 'Calisthenics 9AM', 'HIIT 5PM', 'Open Gym 7PM'] },
      { day: 'Tuesday', classes: ['CrossFit 6AM', 'Bodybuilding 8AM', 'Yoga 5PM', 'Open Gym 7PM'] },
      { day: 'Wednesday', classes: ['CrossFit 6AM', 'Calisthenics 9AM', 'Boxing 5PM', 'Open Gym 7PM'] },
      { day: 'Thursday', classes: ['CrossFit 6AM', 'Bodybuilding 8AM', 'HIIT 5PM', 'Open Gym 7PM'] },
      { day: 'Friday', classes: ['Open Gym 8AM - 12PM'] },
      { day: 'Saturday', classes: ['CrossFit 7AM', 'Community WOD 10AM', 'Open Gym 2PM'] },
    ],
  },
  {
    id: 'g2',
    name: 'FitZone Studio',
    rating: 4.8,
    distance: '2.5 km',
    address: 'Olaya Street, Riyadh',
    lat: 24.6877,
    lng: 46.7219,
    types: ['calisthenics', 'crossfit', 'gym'],
    facilities: ['Pool', 'Sauna', 'Parking', 'Juice Bar', 'Yoga Studio', 'Recovery Room'],
    subscriptions: [
      { name: 'Monthly', price: 350, currency: 'SAR' },
      { name: 'Quarterly', price: 900, currency: 'SAR' },
      { name: 'Yearly', price: 3200, currency: 'SAR' },
    ],
    workingHours: '5:00 AM - 11:00 PM',
    coaches: ['c2'],
    description: 'Modern fitness studio offering a holistic approach to health and fitness with premium amenities.',
    phone: '+966 11 345 6789',
    memberCount: 380,
    events: [
      { id: 'ge3', name: 'Women\'s Fitness Workshop', date: '2026-03-05', time: '10:00 AM', description: 'Free workshop on strength training for women.', attendees: 28 },
    ],
    posts: [
      { id: 'gp4', content: 'Happy to announce our new Recovery Room with cold plunge and infrared sauna!', likes: 324, timestamp: '2026-02-18T10:00:00Z', type: 'text' as const },
      { id: 'gp5', content: 'Juice bar now open! Fresh post-workout smoothies and protein shakes.', likes: 189, timestamp: '2026-02-16T08:00:00Z', type: 'image' as const, imageUrl: 'https://picsum.photos/seed/gympost2/600/400' },
    ],
    schedule: [
      { day: 'Sunday', classes: ['Yoga 6AM', 'CrossFit 8AM', 'Pilates 10AM', 'Strength 5PM'] },
      { day: 'Monday', classes: ['Yoga 6AM', 'HIIT 8AM', 'Swimming 10AM', 'Strength 5PM'] },
      { day: 'Tuesday', classes: ['Yoga 6AM', 'CrossFit 8AM', 'Calisthenics 10AM', 'Strength 5PM'] },
      { day: 'Wednesday', classes: ['Yoga 6AM', 'HIIT 8AM', 'Swimming 10AM', 'Strength 5PM'] },
      { day: 'Thursday', classes: ['Yoga 6AM', 'CrossFit 8AM', 'Calisthenics 10AM', 'Strength 5PM'] },
      { day: 'Friday', classes: ['Community Class 9AM', 'Open Gym 11AM'] },
      { day: 'Saturday', classes: ['Yoga 7AM', 'CrossFit 9AM', 'Open Gym 12PM'] },
    ],
  },
  {
    id: 'g3',
    name: 'PowerHouse Gym',
    rating: 4.5,
    distance: '3.1 km',
    address: 'Exit 5, Northern Ring Road, Riyadh',
    lat: 24.7400,
    lng: 46.7000,
    types: ['bodybuilding', 'gym'],
    facilities: ['Parking', 'Showers', 'Locker Rooms', 'Supplements Store'],
    subscriptions: [
      { name: 'Monthly', price: 150, currency: 'SAR' },
      { name: 'Yearly', price: 1400, currency: 'SAR' },
    ],
    workingHours: '6:00 AM - 11:00 PM',
    coaches: [],
    description: 'No-frills gym focused on serious lifters. Heavy iron, big results.',
    phone: '+966 11 456 7890',
    memberCount: 220,
    events: [],
    posts: [
      { id: 'gp6', content: 'New personal record board is up! Come set your PR and get your name on the wall.', likes: 67, timestamp: '2026-02-19T14:00:00Z', type: 'text' as const },
    ],
    schedule: [
      { day: 'Sunday-Thursday', classes: ['Open Gym 6AM-11PM'] },
      { day: 'Friday', classes: ['Open Gym 8AM-8PM'] },
      { day: 'Saturday', classes: ['Open Gym 6AM-11PM'] },
    ],
  },
];

export type PostType = 'text' | 'image' | 'video' | 'workout_share';

export const posts = [
  {
    id: 'p1',
    userId: 'u1',
    community: 'calisthenics',
    type: 'text' as PostType,
    content: 'Finally nailed my first 10-second free handstand! The journey was worth every second of practice.',
    likes: 142,
    comments: [
      { id: 'cm1', userId: 'u4', text: 'Congrats! How long did it take you?', timestamp: '2026-02-18T10:00:00Z' },
      { id: 'cm2', userId: 'u3', text: 'Amazing work! Next stop: handstand push-ups', timestamp: '2026-02-18T10:30:00Z' },
      { id: 'cm3', userId: 'u2', text: 'So inspiring! Working on mine too.', timestamp: '2026-02-18T11:00:00Z' },
    ],
    timestamp: '2026-02-18T09:30:00Z',
    liked: false,
    saved: false,
  },
  {
    id: 'p2',
    userId: 'u3',
    community: 'gym',
    type: 'workout_share' as PostType,
    content: 'New PR on deadlift today! Consistency pays off. Keep pushing everyone.',
    workoutData: {
      type: 'Pull Day',
      duration: 72,
      exercises: [
        { name: 'Deadlift', sets: [{ reps: 5, weight: 200 }, { reps: 3, weight: 210 }, { reps: 1, weight: 220 }] },
        { name: 'Pull Ups', sets: [{ reps: 12, weight: 0 }, { reps: 10, weight: 0 }, { reps: 8, weight: 10 }] },
        { name: 'Barbell Row', sets: [{ reps: 10, weight: 80 }, { reps: 8, weight: 85 }] },
      ],
      totalVolume: 3840,
    },
    likes: 284,
    comments: [
      { id: 'cm4', userId: 'u1', text: '220kg is insane! Beast mode!', timestamp: '2026-02-18T12:00:00Z' },
      { id: 'cm5', userId: 'u2', text: 'Goals! Great form too.', timestamp: '2026-02-18T12:30:00Z' },
    ],
    timestamp: '2026-02-18T11:45:00Z',
    liked: true,
    saved: false,
  },
  {
    id: 'p3',
    userId: 'u2',
    community: 'running',
    type: 'image' as PostType,
    content: 'Completed my first half marathon in 1:48:32. Next stop: full marathon in April.',
    imageUrl: 'https://picsum.photos/seed/marathon/600/400',
    likes: 198,
    comments: [
      { id: 'cm6', userId: 'u4', text: 'Amazing time! You are going to crush the full.', timestamp: '2026-02-17T17:00:00Z' },
    ],
    timestamp: '2026-02-17T16:20:00Z',
    liked: false,
    saved: true,
  },
  {
    id: 'p4',
    userId: 'u4',
    community: 'calisthenics',
    type: 'video' as PostType,
    content: 'Wall handstand hold for 45 seconds today. Getting closer to freestanding every week!',
    videoThumbnail: 'https://picsum.photos/seed/handstand/600/400',
    likes: 89,
    comments: [],
    timestamp: '2026-02-17T08:15:00Z',
    liked: false,
    saved: false,
  },
  {
    id: 'p5',
    userId: 'u1',
    community: 'gym',
    type: 'workout_share' as PostType,
    content: 'Push day complete. Feeling strong and pumped.',
    workoutData: {
      type: 'Push Day',
      duration: 58,
      exercises: [
        { name: 'Bench Press', sets: [{ reps: 10, weight: 80 }, { reps: 8, weight: 90 }, { reps: 5, weight: 100 }] },
        { name: 'Overhead Press', sets: [{ reps: 10, weight: 50 }, { reps: 8, weight: 55 }, { reps: 8, weight: 60 }] },
        { name: 'Incline Dumbbell Press', sets: [{ reps: 12, weight: 30 }, { reps: 10, weight: 32 }] },
      ],
      totalVolume: 3430,
    },
    likes: 167,
    comments: [
      { id: 'cm7', userId: 'u3', text: '100kg bench! Solid numbers.', timestamp: '2026-02-16T15:00:00Z' },
    ],
    timestamp: '2026-02-16T14:00:00Z',
    liked: true,
    saved: false,
  },
  {
    id: 'p6',
    userId: 'u3',
    community: 'gym',
    type: 'image' as PostType,
    content: 'Back day pump. Nothing beats a good lat spread.',
    imageUrl: 'https://picsum.photos/seed/backday/600/400',
    likes: 231,
    comments: [
      { id: 'cm8', userId: 'u1', text: 'Width goals! What is your back routine?', timestamp: '2026-02-15T11:00:00Z' },
    ],
    timestamp: '2026-02-15T10:30:00Z',
    liked: false,
    saved: false,
  },
];

export const exerciseLibrary = [
  { id: 'e1', name: 'Bench Press', category: 'push', muscleGroup: 'Chest', defaultSetType: 'reps' as const, muscles: ['chest', 'triceps', 'shoulders'] },
  { id: 'e2', name: 'Overhead Press', category: 'push', muscleGroup: 'Shoulders', defaultSetType: 'reps' as const, muscles: ['shoulders', 'triceps'] },
  { id: 'e3', name: 'Incline Dumbbell Press', category: 'push', muscleGroup: 'Chest', defaultSetType: 'reps' as const, muscles: ['chest', 'shoulders'] },
  { id: 'e4', name: 'Tricep Dips', category: 'push', muscleGroup: 'Arms', defaultSetType: 'reps' as const, muscles: ['triceps', 'chest'] },
  { id: 'e5', name: 'Cable Flyes', category: 'push', muscleGroup: 'Chest', defaultSetType: 'reps' as const, muscles: ['chest'] },
  { id: 'e6', name: 'Deadlift', category: 'pull', muscleGroup: 'Back', defaultSetType: 'reps' as const, muscles: ['back', 'hamstrings', 'glutes'] },
  { id: 'e7', name: 'Pull Ups', category: 'pull', muscleGroup: 'Back', defaultSetType: 'reps' as const, muscles: ['back', 'biceps'] },
  { id: 'e8', name: 'Barbell Row', category: 'pull', muscleGroup: 'Back', defaultSetType: 'reps' as const, muscles: ['back', 'biceps'] },
  { id: 'e9', name: 'Face Pulls', category: 'pull', muscleGroup: 'Shoulders', defaultSetType: 'reps' as const, muscles: ['rear delts', 'traps'] },
  { id: 'e10', name: 'Bicep Curls', category: 'pull', muscleGroup: 'Arms', defaultSetType: 'reps' as const, muscles: ['biceps'] },
  { id: 'e11', name: 'Squat', category: 'legs', muscleGroup: 'Legs', defaultSetType: 'reps' as const, muscles: ['quads', 'glutes'] },
  { id: 'e12', name: 'Romanian Deadlift', category: 'legs', muscleGroup: 'Legs', defaultSetType: 'reps' as const, muscles: ['hamstrings', 'glutes'] },
  { id: 'e13', name: 'Leg Press', category: 'legs', muscleGroup: 'Legs', defaultSetType: 'reps' as const, muscles: ['quads', 'glutes'] },
  { id: 'e14', name: 'Leg Curl', category: 'legs', muscleGroup: 'Legs', defaultSetType: 'reps' as const, muscles: ['hamstrings'] },
  { id: 'e15', name: 'Calf Raises', category: 'legs', muscleGroup: 'Legs', defaultSetType: 'reps' as const, muscles: ['calves'] },
  { id: 'e16', name: 'Plank', category: 'core', muscleGroup: 'Core', defaultSetType: 'hold' as const, muscles: ['core'] },
  { id: 'e17', name: 'Handstand Hold', category: 'calisthenics', muscleGroup: 'Calisthenics', defaultSetType: 'hold' as const, muscles: ['shoulders', 'core'] },
  { id: 'e18', name: 'Muscle Up', category: 'calisthenics', muscleGroup: 'Calisthenics', defaultSetType: 'reps' as const, muscles: ['back', 'chest', 'triceps'] },
  { id: 'e19', name: 'Front Lever', category: 'calisthenics', muscleGroup: 'Calisthenics', defaultSetType: 'hold' as const, muscles: ['back', 'core'] },
  { id: 'e20', name: 'L-Sit', category: 'calisthenics', muscleGroup: 'Core', defaultSetType: 'hold' as const, muscles: ['core', 'hip flexors'] },
  { id: 'e21', name: 'Lateral Raises', category: 'push', muscleGroup: 'Shoulders', defaultSetType: 'reps' as const, muscles: ['shoulders'] },
  { id: 'e22', name: 'Hammer Curls', category: 'pull', muscleGroup: 'Arms', defaultSetType: 'reps' as const, muscles: ['biceps', 'forearms'] },
  { id: 'e23', name: 'Leg Extensions', category: 'legs', muscleGroup: 'Legs', defaultSetType: 'reps' as const, muscles: ['quads'] },
  { id: 'e24', name: 'Hip Thrusts', category: 'legs', muscleGroup: 'Legs', defaultSetType: 'reps' as const, muscles: ['glutes', 'hamstrings'] },
  { id: 'e25', name: 'Push Ups', category: 'push', muscleGroup: 'Chest', defaultSetType: 'reps' as const, muscles: ['chest', 'triceps'] },
  { id: 'e26', name: 'Dumbbell Shoulder Press', category: 'push', muscleGroup: 'Shoulders', defaultSetType: 'reps' as const, muscles: ['shoulders'] },
  { id: 'e27', name: 'Tricep Pushdown', category: 'push', muscleGroup: 'Arms', defaultSetType: 'reps' as const, muscles: ['triceps'] },
  { id: 'e28', name: 'Lat Pulldown', category: 'pull', muscleGroup: 'Back', defaultSetType: 'reps' as const, muscles: ['back', 'biceps'] },
  { id: 'e29', name: 'Seated Cable Row', category: 'pull', muscleGroup: 'Back', defaultSetType: 'reps' as const, muscles: ['back'] },
  { id: 'e30', name: 'Wall Sit', category: 'legs', muscleGroup: 'Legs', defaultSetType: 'hold' as const, muscles: ['quads'] },
  { id: 'e31', name: 'Ab Crunches', category: 'core', muscleGroup: 'Core', defaultSetType: 'reps' as const, muscles: ['core'] },
  { id: 'e32', name: 'Russian Twist', category: 'core', muscleGroup: 'Core', defaultSetType: 'reps' as const, muscles: ['core', 'obliques'] },
  { id: 'e33', name: 'Burpees', category: 'cardio', muscleGroup: 'Full Body', defaultSetType: 'reps' as const, muscles: ['full body'] },
  { id: 'e34', name: 'Mountain Climbers', category: 'cardio', muscleGroup: 'Full Body', defaultSetType: 'reps' as const, muscles: ['core', 'full body'] },
  { id: 'e35', name: 'Box Jumps', category: 'cardio', muscleGroup: 'Full Body', defaultSetType: 'reps' as const, muscles: ['legs', 'full body'] },
  { id: 'e36', name: 'Chest Dips', category: 'push', muscleGroup: 'Chest', defaultSetType: 'reps' as const, muscles: ['chest', 'triceps'] },
];

export const MUSCLE_GROUPS = ['Chest', 'Back', 'Shoulders', 'Arms', 'Legs', 'Core', 'Cardio', 'Calisthenics', 'Full Body'];

export const foodDatabase = [
  { id: 'f1', name: 'Chicken Breast (100g)', protein: 31, carbs: 0, fat: 3.6, calories: 165 },
  { id: 'f2', name: 'Eggs (1 large)', protein: 6, carbs: 0.6, fat: 5, calories: 72 },
  { id: 'f3', name: 'White Rice (100g)', protein: 2.7, carbs: 28, fat: 0.3, calories: 130 },
  { id: 'f4', name: 'Oats (100g)', protein: 13, carbs: 66, fat: 7, calories: 389 },
  { id: 'f5', name: 'Greek Yogurt (100g)', protein: 10, carbs: 3.6, fat: 0.7, calories: 59 },
  { id: 'f6', name: 'Banana (1 medium)', protein: 1.3, carbs: 27, fat: 0.4, calories: 105 },
  { id: 'f7', name: 'Brown Rice (100g)', protein: 2.6, carbs: 23, fat: 0.9, calories: 112 },
  { id: 'f8', name: 'Salmon (100g)', protein: 20, carbs: 0, fat: 13, calories: 208 },
  { id: 'f9', name: 'Sweet Potato (100g)', protein: 1.6, carbs: 20, fat: 0.1, calories: 86 },
  { id: 'f10', name: 'Peanut Butter (2 tbsp)', protein: 8, carbs: 6, fat: 16, calories: 190 },
  { id: 'f11', name: 'Whey Protein (1 scoop)', protein: 25, carbs: 3, fat: 1, calories: 120 },
  { id: 'f12', name: 'Avocado (1 medium)', protein: 3, carbs: 12, fat: 21, calories: 240 },
  { id: 'f13', name: 'Tuna (100g)', protein: 30, carbs: 0, fat: 1, calories: 132 },
  { id: 'f14', name: 'Almonds (30g)', protein: 6, carbs: 6, fat: 14, calories: 164 },
  { id: 'f15', name: 'Milk (250ml)', protein: 8, carbs: 12, fat: 8, calories: 149 },
];

export const tournaments = [
  {
    id: 't1',
    name: 'Riyadh Calisthenics Open 2026',
    sport: 'calisthenics',
    date: '2026-03-15',
    location: 'Al Malaz Sports Hall, Riyadh',
    lat: 24.6580,
    lng: 46.7100,
    levels: ['Beginner', 'Intermediate', 'Pro'],
    awards: ['SAR 5,000', 'SAR 2,500', 'SAR 1,000'],
    registeredCount: 48,
    organizer: 'g1',
    description: 'Annual calisthenics competition featuring freestyle, statics, and endurance categories.',
  },
  {
    id: 't2',
    name: 'Saudi CrossFit Championship',
    sport: 'crossfit',
    date: '2026-04-20',
    location: 'King Abdullah Sports City, Jeddah',
    lat: 21.7143,
    lng: 39.1042,
    levels: ['Intermediate', 'Pro'],
    awards: ['SAR 10,000', 'SAR 5,000', 'SAR 2,500'],
    registeredCount: 120,
    organizer: 'g2',
    description: 'The biggest CrossFit event in the kingdom. Multiple WODs across 2 days.',
  },
  {
    id: 't3',
    name: 'Riyadh Running Festival',
    sport: 'running',
    date: '2026-05-10',
    location: 'King Fahad Park, Riyadh',
    lat: 24.7500,
    lng: 46.6500,
    levels: ['Beginner', 'Intermediate', 'Pro'],
    awards: ['SAR 8,000', 'SAR 4,000', 'SAR 2,000'],
    registeredCount: 340,
    organizer: 'g1',
    description: '5K, 10K, and Half Marathon through the heart of Riyadh.',
  },
];

export const restaurants = [
  {
    id: 'r1',
    name: 'FitBite Kitchen',
    rating: 4.5,
    distance: '0.8 km',
    address: 'Tahlia Street, Riyadh',
    lat: 24.6900,
    lng: 46.6850,
    phone: '+966 11 567 8901',
    workingHours: '7:00 AM - 11:00 PM',
    description: 'Healthy meals crafted for athletes. Every dish comes with full macro breakdown. We source organic, local ingredients.',
    tags: ['High Protein', 'Meal Prep', 'Organic'],
    menu: [
      { name: 'Grilled Chicken Plate', protein: 45, carbs: 30, fat: 8, calories: 372, price: 35, currency: 'SAR' },
      { name: 'Salmon Bowl', protein: 38, carbs: 45, fat: 15, calories: 467, price: 48, currency: 'SAR' },
      { name: 'Protein Smoothie', protein: 30, carbs: 20, fat: 5, calories: 245, price: 22, currency: 'SAR' },
      { name: 'Steak & Sweet Potato', protein: 52, carbs: 35, fat: 12, calories: 456, price: 55, currency: 'SAR' },
      { name: 'Protein Pancakes', protein: 28, carbs: 40, fat: 8, calories: 344, price: 25, currency: 'SAR' },
    ],
  },
  {
    id: 'r2',
    name: 'Clean Eats',
    rating: 4.7,
    distance: '1.5 km',
    address: 'Olaya District, Riyadh',
    lat: 24.7050,
    lng: 46.7100,
    phone: '+966 11 678 9012',
    workingHours: '8:00 AM - 10:00 PM',
    description: 'Clean eating made delicious. Macro-tracked meals for fitness enthusiasts. Delivery available.',
    tags: ['Low Carb', 'Keto Friendly', 'Delivery'],
    menu: [
      { name: 'Turkey Wrap', protein: 35, carbs: 28, fat: 10, calories: 342, price: 30, currency: 'SAR' },
      { name: 'Quinoa Salad', protein: 18, carbs: 40, fat: 12, calories: 340, price: 28, currency: 'SAR' },
      { name: 'Steak & Veggies', protein: 50, carbs: 15, fat: 18, calories: 422, price: 55, currency: 'SAR' },
      { name: 'Protein Bowl', protein: 42, carbs: 50, fat: 14, calories: 494, price: 40, currency: 'SAR' },
      { name: 'Green Detox Juice', protein: 2, carbs: 15, fat: 0, calories: 68, price: 18, currency: 'SAR' },
    ],
  },
  {
    id: 'r3',
    name: 'Fuel Station',
    rating: 4.3,
    distance: '2.2 km',
    address: 'Al Nakheel, Riyadh',
    lat: 24.7300,
    lng: 46.6600,
    phone: '+966 11 789 0123',
    workingHours: '6:00 AM - 12:00 AM',
    description: 'Pre and post-workout fuel. Smoothie bar, energy bowls, and high-protein meals designed for peak performance.',
    tags: ['Smoothies', 'Pre-Workout', 'Post-Workout'],
    menu: [
      { name: 'Power Smoothie', protein: 35, carbs: 30, fat: 6, calories: 314, price: 24, currency: 'SAR' },
      { name: 'Acai Bowl', protein: 12, carbs: 55, fat: 8, calories: 340, price: 32, currency: 'SAR' },
      { name: 'Chicken & Rice Box', protein: 48, carbs: 60, fat: 10, calories: 522, price: 38, currency: 'SAR' },
    ],
  },
];

export const workoutTypes = [
  { id: 'push', name: 'Push Day', icon: 'arrow-up-circle-outline' },
  { id: 'pull', name: 'Pull Day', icon: 'arrow-down-circle-outline' },
  { id: 'legs', name: 'Leg Day', icon: 'walk-outline' },
  { id: 'upper', name: 'Upper Body', icon: 'body-outline' },
  { id: 'full', name: 'Full Body', icon: 'fitness-outline' },
  { id: 'cardio', name: 'Cardio', icon: 'heart-outline' },
  { id: 'custom', name: 'Custom', icon: 'create-outline' },
];

export const aiTips = [
  'Your bench press has improved 15% this month. Keep up the progressive overload!',
  'You seem to skip leg day often. Consider adding at least one leg session per week.',
  'Your protein intake has been below target for 3 days. Try adding a protein shake post-workout.',
  'Great consistency this week! 5 workouts in a row. Rest is important too - take a day off.',
  'Based on your sleep patterns, morning workouts may give you better performance.',
  'Your deadlift form might benefit from incorporating Romanian deadlifts as an accessory.',
];

export const ranks = [
  { id: 'beginner_athlete', name: 'Beginner Athlete', icon: 'medal-outline', color: '#A0A0B0', minWorkouts: 0 },
  { id: 'active_athlete', name: 'Active Athlete', icon: 'medal-outline', color: '#4ECDC4', minWorkouts: 20 },
  { id: 'competitive_athlete', name: 'Competitive Athlete', icon: 'trophy-outline', color: '#FFD700', minWorkouts: 50 },
  { id: 'elite_athlete', name: 'Elite Athlete', icon: 'diamond-outline', color: '#00B4D8', minWorkouts: 100 },
  { id: 'champion', name: 'Champion', icon: 'trophy', color: '#FF6B35', minWorkouts: 200 },
];

export const sportInterests = [
  { id: 'calisthenics', name: 'Calisthenics', icon: 'body-outline' },
  { id: 'gym', name: 'Gym / Weightlifting', icon: 'barbell-outline' },
  { id: 'football', name: 'Football', icon: 'football-outline' },
  { id: 'tennis', name: 'Tennis', icon: 'tennisball-outline' },
  { id: 'running', name: 'Running', icon: 'walk-outline' },
  { id: 'swimming', name: 'Swimming', icon: 'water-outline' },
  { id: 'crossfit', name: 'CrossFit', icon: 'fitness-outline' },
];

export const goals = [
  { id: 'build_muscle', icon: 'barbell-outline' },
  { id: 'lose_weight', icon: 'flame-outline' },
  { id: 'learn_skill', icon: 'school-outline' },
  { id: 'improve_fitness', icon: 'trending-up-outline' },
];

export interface ReadyUser {
  userId: string;
  activity: string;
  location: string;
  lat: number;
  lng: number;
  status: 'ready' | 'scheduled';
  scheduledTime?: string;
}

export const readyToTrainUsers: ReadyUser[] = [
  { userId: 'u1', activity: 'calisthenics', location: 'Al Malaz Park', lat: 24.6600, lng: 46.7100, status: 'ready' },
  { userId: 'u2', activity: 'running', location: 'King Fahad Park', lat: 24.7500, lng: 46.6500, status: 'ready' },
  { userId: 'u3', activity: 'gym', location: 'Iron Peak Gym', lat: 24.7136, lng: 46.6753, status: 'scheduled', scheduledTime: '2026-02-21T08:00:00Z' },
  { userId: 'u4', activity: 'calisthenics', location: 'FitZone Studio', lat: 24.6877, lng: 46.7219, status: 'ready' },
];
