// Compile the 6 authoring-batch JSONL files into a single seed data module:
//   server/modules/workout/seed-data/exercises-hevy.data.ts
// Validates: valid body-target enum, targets sum to 100 (auto-fixes small rounding
// drift onto the largest target), valid measurement, non-empty types.
// Run AFTER the authoring agents finish: node scripts/compile-hevy.mjs
import fs from 'fs';

const ENUM = new Set(['chest','shoulders_anterior','shoulders_lateral','shoulders_posterior','triceps','biceps','forearms','lats','upper_back','mid_back','lower_back','traps','erector_spinae','core_abs','core_deep','obliques','hip_flexors','glutes','hamstrings','quadriceps','adductors','calves','cardiovascular','flexibility','balance','endurance']);
const TYPES = new Set(['Push Day','Pull Day','Leg Day','Upper Body','Lower Body','Core','Full Body','HIIT','Cardio','Calisthenics','Mobility','Functional','Olympic Lifting','Powerlifting','CrossFit / WOD']);
const MEAS = new Set(['reps','time_hold','distance_duration']);

const files = fs.readdirSync('/tmp').filter(f => /^hevy_out_/.test(f)).map(f => '/tmp/' + f);
const seen = new Map();
let bad = [];
for (const f of files) {
  for (const line of fs.readFileSync(f, 'utf8').split('\n')) {
    const s = line.trim(); if (!s) continue;
    let o; try { o = JSON.parse(s); } catch { bad.push('JSON parse: ' + s.slice(0, 60)); continue; }
    if (!o.name) { bad.push('no name'); continue; }
    if (seen.has(o.name)) continue;
    // validate/fix targets
    let t = (o.targets || []).filter(x => x && ENUM.has(x.bodyTarget) && Number.isFinite(x.percentage));
    if (!t.length) { bad.push('no valid targets: ' + o.name); continue; }
    let sum = t.reduce((a, x) => a + Math.round(x.percentage), 0);
    t = t.map(x => ({ bodyTarget: x.bodyTarget, percentage: Math.round(x.percentage) }));
    if (sum !== 100) { // dump drift onto the largest
      t.sort((a, b) => b.percentage - a.percentage);
      t[0].percentage += (100 - sum);
      if (t[0].percentage <= 0) { bad.push('bad sum unfixable: ' + o.name); continue; }
    }
    const types = (o.types || []).filter(x => TYPES.has(x));
    const measurement = MEAS.has(o.measurement) ? o.measurement : 'reps';
    seen.set(o.name, {
      name: o.name,
      description: (o.descEn || '').trim(),
      descriptionAr: (o.descAr || '').trim(),
      measurement,
      types: types.length ? types : ['Full Body'],
      targets: t,
    });
  }
}

const list = [...seen.values()].sort((a, b) => a.name.localeCompare(b.name));
const q = s => JSON.stringify(s);
const out = `// AUTO-GENERATED by scripts/compile-hevy.mjs from the authoring batches.
// Original descriptions (EN + AR), correct weighted body-targets (sum 100),
// categories + measurement. Equipment + image come from exercise-meta.map.ts.
export interface HevyExercise {
  name: string; description: string; descriptionAr: string;
  measurement: "reps" | "time_hold" | "distance_duration";
  types: string[]; targets: { bodyTarget: string; percentage: number }[];
}
export const HEVY_EXERCISES: HevyExercise[] = ${JSON.stringify(list, null, 0)};
`;
fs.writeFileSync('server/modules/workout/seed-data/exercises-hevy.data.ts', out);
console.log(`compiled ${list.length} exercises | issues ${bad.length}`);
if (bad.length) console.log(bad.slice(0, 20).join('\n'));
