// AUTO-GENERATED (Fable authoring batches) — human MSA gym names for the
// Hevy-catalog exercises that had no curated Arabic name. Merged into NAME_AR
// in exercise-ar.seed.ts. Regenerate: re-run the ar-name authoring batches.
export const HEVY_NAME_AR: Record<string, string> = {
  "21s Bicep Curl": "مرجحة البايسبس (تمرين 21)",
  "Ab Scissors": "مقص البطن",
  "Ab Wheel": "عجلة البطن",
  "Aerobics": "تمارين الأيروبيك",
  "Air Bike": "دراجة الإير بايك",
  "Arnold Press (Dumbbell)": "ضغط أرنولد بالدمبل",
  "Around The World": "تمرين حول العالم",
  "Assisted Pistol Squats": "قرفصاء بيستول بمساعدة",
  "Back Extension (Hyperextension)": "تمديد الظهر (هايبر إكستنشن)",
  "Back Extension (Machine)": "تمديد الظهر بالجهاز",
  "Back Extension (Weighted Hyperextension)": "تمديد الظهر بوزن إضافي (هايبر إكستنشن)",
  "Ball Slams": "ضرب الكرة الطبية بالأرض",
  "Band Pullaparts": "شد المطاط للجانبين",
  "Bear Crawl": "زحف الدب",
  "Behind the Back Curl (Cable)": "مرجحة البايسبس خلف الظهر بالكابل",
  "Behind the Back Wrist Curl (Barbell)": "ثني الرسغ خلف الظهر بالبار",
  "Belt Squat (Machine)": "قرفصاء الحزام بالجهاز",
  "Bench Press (Barbell)": "ضغط البار",
  "Bench Press (Cable)": "ضغط الصدر بالكابل",
  "Bench Press (Dumbbell)": "ضغط الصدر بالدمبل",
  "Bench Press (Smith Machine)": "ضغط الصدر بجهاز سميث",
  "Bench Press - Close Grip (Barbell)": "ضغط البار بقبضة ضيقة",
  "Bench Press - Wide Grip (Barbell)": "ضغط البار بقبضة واسعة",
  "Bent Over Row (Band)": "التجديف بالانحناء بالمطاط",
  "Bent Over Row (Barbell)": "التجديف بالانحناء بالبار",
  "Bent Over Row (Dumbbell)": "التجديف بالانحناء بالدمبل",
  "Bent Over Row (Smith Machine)": "التجديف بالانحناء بجهاز سميث",
  "Bicep Curl (Barbell)": "مرجحة البايسبس بالبار",
  "Bicep Curl (Cable)": "مرجحة البايسبس بالكابل",
  "Bicep Curl (Dumbbell)": "مرجحة البايسبس بالدمبل",
  "Bicep Curl (Machine)": "مرجحة البايسبس بالجهاز",
  "Bicep Curl (Suspension)": "مرجحة البايسبس بحبال التعليق",
  "Bicycle Crunch Raised Legs": "كرنش الدراجة مع رفع الساقين",
  "Bird Dog": "تمرين بيرد دوغ",
  "Box Squat (Barbell)": "قرفصاء الصندوق بالبار",
  "Boxing": "ملاكمة",
  "Bulgarian Split Squat (Barbell)": "القرفصاء البلغارية بالبار",
  "Bulgarian Split Squat (Dumbbell)": "القرفصاء البلغارية بالدمبل",
  "Burpee Broad Jumps": "بيربي مع القفز العريض",
  "Burpee Over the Bar": "بيربي فوق البار",
  "Butterfly (Pec Deck)": "الفراشة (بيك ديك)",
  "Cable Core Pallof Press": "ضغط بالوف بالكابل",
  "Cable Fly Crossovers": "التفتيح المتقاطع بالكابل (كروس أوفر)",
  "Cable Pull Through": "سحب الكابل بين الساقين",
  "Cable Twist (Down to up)": "لف الجذع بالكابل من الأسفل للأعلى",
  "Cable Twist (Up to down)": "لف الجذع بالكابل من الأعلى للأسفل",
  "Calf Extension (Machine)": "تمديد السمانة بالجهاز",
  "Calf Press (Machine)": "ضغط السمانة بالجهاز",
  "Chest Dip": "متوازي الصدر (ديبس)",
  "Chest Dip (Assisted)": "متوازي الصدر بمساعدة",
  "Chest Dip (Weighted)": "متوازي الصدر بوزن إضافي",
  "Chest Fly (Band)": "تفتيح الصدر بالمطاط",
  "Chest Fly (Dumbbell)": "تفتيح الصدر بالدمبل",
  "Chest Fly (Machine)": "تفتيح الصدر بالجهاز",
  "Chest Fly (Suspension)": "تفتيح الصدر بحبال التعليق",
  "Chest Press (Band)": "ضغط الصدر بالمطاط",
  "Chest Press (Machine)": "ضغط الصدر بالجهاز",
  "Chest Supported Incline Row (Dumbbell)": "التجديف المائل بالدمبل بإسناد الصدر",
  "Chest Supported Reverse Fly (Dumbbell)": "الرفرفة العكسية بالدمبل بإسناد الصدر",
  "Chest Supported T Bar Row": "تجديف التي بار بإسناد الصدر",
  "Chest Supported Y Raise (Dumbbell)": "رفعة Y بالدمبل بإسناد الصدر",
  "Chin Up (Assisted)": "العقلة بقبضة عكسية بمساعدة",
  "Chin Up (Weighted)": "العقلة بقبضة عكسية بوزن إضافي",
  "Clamshell": "تمرين المحارة (كلام شيل)",
  "Clap Push Ups": "الضغط مع التصفيق",
  "Clean": "الكلين",
  "Clean Pull": "سحبة الكلين",
  "Clean and Jerk": "الكلين والجيرك (النتر)",
  "Clean and Press": "الكلين مع الضغط",
  "Climbing": "التسلق",
  "Cross Body Hammer Curl": "مرجحة المطرقة المتقاطعة",
  "Crunch (Machine)": "كرنش بالجهاز",
  "Crunch (Weighted)": "كرنش بوزن",
  "Curtsy Lunge (Dumbbell)": "طعنة كيرتسي بالدمبل",
  "Cycling": "ركوب الدراجة",
  "Deadlift (Band)": "الرفعة الميتة بالمطاط",
  "Deadlift (Barbell)": "الرفعة الميتة بالبار",
  "Deadlift (Dumbbell)": "الرفعة الميتة بالدمبل",
  "Deadlift (Smith Machine)": "الرفعة الميتة بجهاز سميث",
  "Deadlift (Trap bar)": "الرفعة الميتة بالبار السداسي",
  "Deadlift High Pull": "الرفعة الميتة مع السحب العالي",
  "Decline Bench Press (Barbell)": "ضغط البار المنحدر",
  "Decline Bench Press (Dumbbell)": "ضغط الدمبل المنحدر",
  "Decline Bench Press (Machine)": "ضغط الصدر المنحدر بالجهاز",
  "Decline Bench Press (Smith Machine)": "الضغط المنحدر بجهاز سميث",
  "Decline Chest Fly (Dumbbell)": "تفتيح الصدر المنحدر بالدمبل",
  "Decline Crunch": "كرنش منحدر",
  "Decline Crunch (Weighted)": "كرنش منحدر بوزن",
  "Decline Push Up": "الضغط المنحدر",
  "Downward Dog": "وضعية الكلب المقلوب",
  "Drag Curl": "مرجحة دراغ",
  "Dragonfly": "دراغون فلاي",
  "Dumbbell Snatch": "الخطف بالدمبل",
  "Dumbbell Squeeze Press": "ضغط الضم بالدمبل",
  "EZ Bar Biceps Curl": "مرجحة البايسبس بالبار المعقوف",
  "Elbow to Knee": "الكوع إلى الركبة",
  "Elliptical Trainer": "جهاز الإلبتيكال",
  "Farmers Walk": "مشية الفلاح",
  "Feet Up Bench Press (Barbell)": "ضغط البار مع رفع القدمين",
  "Fire Hydrants": "فاير هايدرانت",
  "Floor Press (Barbell)": "الضغط الأرضي بالبار",
  "Floor Press (Dumbbell)": "الضغط الأرضي بالدمبل",
  "Floor Triceps Dip": "غطس الترايسبس الأرضي",
  "Flutter Kicks": "الركلات المتناوبة",
  "Frog Jumps": "قفزات الضفدع",
  "Frog Pumps (Dumbbell)": "جسر الضفدع بالدمبل",
  "Front Lever Hold": "ثبات الفرونت ليفر",
  "Front Lever Raise": "رفع الفرونت ليفر",
  "Front Raise (Band)": "الرفع الأمامي بالمطاط",
  "Front Raise (Barbell)": "الرفع الأمامي بالبار",
  "Front Raise (Cable)": "الرفع الأمامي بالكابل",
  "Front Raise (Dumbbell)": "الرفع الأمامي بالدمبل",
  "Front Raise (Suspension)": "الرفع الأمامي بحبال التعليق",
  "Full Squat": "القرفصاء الكاملة",
  "Glute Bridge (Barbell)": "جسر المؤخرة بالبار",
  "Glute Ham Raise": "رفعة الجلوت هام",
  "Glute Kickback (Machine)": "الركلة الخلفية للمؤخرة بالجهاز",
  "Glute Kickback on Floor": "الركلة الخلفية للمؤخرة على الأرض",
  "Good Morning (Barbell)": "صباح الخير بالبار",
  "Gorilla Row (Kettlebell)": "تجديف الغوريلا بالكيتل بِل",
  "HIIT": "هيت (تدريب متقطع عالي الشدة)",
  "Hack Squat (Machine)": "قرفصاء الهاك بالجهاز",
  "Hammer Curl (Band)": "مرجحة المطرقة بالمطاط",
  "Hammer Curl (Cable)": "مرجحة المطرقة بالكابل",
  "Hammer Curl (Dumbbell)": "مرجحة المطرقة بالدمبل",
  "Hang Snatch": "الخطف من التعلق",
  "Heel Taps": "لمس الكعبين",
  "Hex Press (Dumbbell)": "ضغط هيكس بالدمبل",
  "High Knee Skips": "القفز برفع الركبتين",
  "Hiking": "المشي الجبلي (هايكنج)",
  "Hip Abduction (Cable)": "تبعيد الورك بالكابل",
  "Hip Adduction (Cable)": "تقريب الورك بالكابل",
  "Hip Thrust (Barbell)": "دفع الورك بالبار",
  "Hip Thrust (Dumbbell)": "دفع الورك بالدمبل",
  "Hip Thrust (Machine)": "دفع الورك بالجهاز",
  "Hip Thrust (Smith Machine)": "دفع الورك بجهاز سميث",
  "Hollow Rock": "تأرجح هولو روك",
  "Incline Bench Press (Barbell)": "ضغط البار المائل",
  "Incline Bench Press (Dumbbell)": "ضغط الصدر المائل بالدمبل",
  "Incline Bench Press (Smith Machine)": "ضغط الصدر المائل بجهاز سميث",
  "Incline Chest Fly (Dumbbell)": "تفتيح الصدر المائل بالدمبل",
  "Incline Chest Press (Machine)": "ضغط الصدر المائل بالجهاز",
  "Incline Push Ups": "تمرين الضغط المائل",
  "Iso-Lateral Chest Press (Machine)": "ضغط الصدر أيزو بالجهاز",
  "Iso-Lateral High Row (Machine)": "التجديف العالي أيزو بالجهاز",
  "Iso-Lateral Low Row": "التجديف المنخفض أيزو",
  "Iso-Lateral Row (Machine)": "التجديف أيزو بالجهاز",
  "JM Press (Barbell)": "ضغط جي إم بالبار",
  "Jack Knife (Suspension)": "جاك نايف بحبال التعليق",
  "Jackknife Sit Up": "تمرين المعدة جاك نايف",
  "Jump Shrug": "هز الأكتاف بالقفز",
  "Jump Squat": "القرفصاء بالقفز",
  "Jumping Lunge": "الطعنات بالقفز",
  "Kettlebell Around the World": "تدوير الكيتل بِل حول الجسم",
  "Kettlebell Clean": "كلين بالكيتل بِل",
  "Kettlebell Curl": "مرجحة البايسبس بالكيتل بِل",
  "Kettlebell Goblet Squat": "قرفصاء جوبلت بالكيتل بِل",
  "Kettlebell Halo": "هالو بالكيتل بِل",
  "Kettlebell High Pull": "السحب العالي بالكيتل بِل",
  "Kettlebell Shoulder Press": "ضغط الكتف بالكيتل بِل",
  "Kettlebell Snatch": "سناتش بالكيتل بِل",
  "Kettlebell Turkish Get Up": "النهوض التركي بالكيتل بِل",
  "Kipping Pull Up": "عقلة كيبينغ",
  "Knee Raise Parallel Bars": "رفع الركبتين على المتوازي",
  "Kneeling Pulldown (band)": "سحب أمامي بالمطاط جاثياً",
  "Kneeling Push Up": "الضغط على الركبتين",
  "L-Sit Hold": "ثبات وضعية L",
  "Landmine 180": "دوران لاند ماين 180",
  "Landmine Row": "تجديف لاند ماين",
  "Landmine Squat and Press": "قرفصاء وضغط لاند ماين",
  "Lat Pulldown (Band)": "سحب أمامي بالمطاط",
  "Lat Pulldown (Cable)": "السحب الأمامي بالكابل",
  "Lat Pulldown (Machine)": "السحب الأمامي بالجهاز",
  "Lat Pulldown - Close Grip (Cable)": "سحب أمامي بقبضة ضيقة بالكابل",
  "Lateral Band Walks": "المشي الجانبي بالمطاط",
  "Lateral Box Jump": "القفز الجانبي على الصندوق",
  "Lateral Leg Raises": "رفع الساق الجانبي",
  "Lateral Lunge": "الطعنة الجانبية",
  "Lateral Raise (Band)": "الرفرفة الجانبية بالمطاط",
  "Lateral Raise (Cable)": "الرفرفة الجانبية بالكابل",
  "Lateral Raise (Dumbbell)": "الرفرفة الجانبية بالدمبل",
  "Lateral Raise (Machine)": "الرفرفة الجانبية بالجهاز",
  "Lateral Squat": "القرفصاء الجانبية",
  "Leg Extension (Machine)": "تمديد الأرجل بالجهاز",
  "Leg Press (Machine)": "ضغط الأرجل بالجهاز",
  "Leg Press Horizontal (Machine)": "ضغط الأرجل الأفقي بالجهاز",
  "Leg Raise Parallel Bars": "رفع الأرجل على المتوازي",
  "Low Cable Fly Crossovers": "التفتيح المتقاطع بالكابل السفلي",
  "Low Row (Suspension)": "التجديف المنخفض بحبال التعليق",
  "Lunge": "الطعنات",
  "Lunge (Barbell)": "الطعنات بالبار",
  "Lunge (Dumbbell)": "الطعنات بالدمبل",
  "Lying Knee Raise": "رفع الركبتين مستلقياً",
  "Lying Leg Curl (Machine)": "ثني الرجلين مستلقياً بالجهاز",
  "Lying Neck Curls": "ثني الرقبة مستلقياً",
  "Lying Neck Curls (Weighted)": "ثني الرقبة مستلقياً بوزن",
  "Lying Neck Extension": "تمديد الرقبة مستلقياً",
  "Lying Neck Extension (Weighted)": "تمديد الرقبة مستلقياً بوزن",
  "Meadows Rows (Barbell)": "تجديف ميدوز بالبار",
  "Negative Pull Up": "العقلة السلبية",
  "Nordic Hamstrings Curls": "ثني نورديك لخلفية الفخذ",
  "Oblique Crunch": "كرنش جانبي للجوانب",
  "One Arm Push Up": "ضغط بذراع واحدة",
  "Overhead Curl (Cable)": "مرجحة البايسبس فوق الرأس بالكابل",
  "Overhead Dumbbell Lunge": "طعنة بالدمبل فوق الرأس",
  "Overhead Plate Raise": "رفع البلايت فوق الرأس",
  "Overhead Press (Dumbbell)": "ضغط الكتف بالدمبل",
  "Overhead Press (Smith Machine)": "ضغط الكتف بجهاز سميث",
  "Overhead Squat": "قرفصاء والبار فوق الرأس",
  "Overhead Triceps Extension (Cable)": "تمديد الترايسبس فوق الرأس بالكابل",
  "Partial Glute Bridge (Barbell)": "جسر المؤخرة الجزئي بالبار",
  "Pause Squat (Barbell)": "قرفصاء مع توقف بالبار",
  "Pendlay Row (Barbell)": "تجديف بندلاي بالبار",
  "Pendulum Squat (Machine)": "قرفصاء البندول بالجهاز",
  "Pilates": "بيلاتس",
  "Pinwheel Curl (Dumbbell)": "مرجحة بينويل بالدمبل",
  "Plank Pushup": "بلانك مع ضغط",
  "Plate Curl": "مرجحة البايسبس بالبلايت",
  "Plate Front Raise": "الرفع الأمامي بالبلايت",
  "Plate Press": "ضغط البلايت",
  "Plate Squeeze (Svend Press)": "ضغط سفيند (عصر البلايت)",
  "Preacher Curl (Barbell)": "مرجحة بريتشر بالبار",
  "Preacher Curl (Dumbbell)": "مرجحة بريتشر بالدمبل",
  "Preacher Curl (Machine)": "مرجحة بريتشر بالجهاز",
  "Press Under": "الضغط تحت البار",
  "Pull Up (Assisted)": "عقلة بمساعدة",
  "Pull Up (Band)": "عقلة بالمطاط",
  "Pull Up (Weighted)": "عقلة بوزن إضافي",
  "Pullover (Dumbbell)": "بول أوفر بالدمبل",
  "Pullover (Machine)": "بول أوفر بالجهاز",
  "Push Press": "ضغط الكتف بالدفع",
  "Push Up (Weighted)": "ضغط بوزن إضافي",
  "Push Up - Close Grip": "ضغط بقبضة ضيقة",
  "Rack Pull": "سحبة الراك",
  "Rear Delt Reverse Fly (Cable)": "التفتيح العكسي للكتف الخلفي بالكابل",
  "Rear Delt Reverse Fly (Dumbbell)": "التفتيح العكسي للكتف الخلفي بالدمبل",
  "Rear Delt Reverse Fly (Machine)": "التفتيح العكسي للكتف الخلفي بالجهاز",
  "Rear Kick (Machine)": "الركلة الخلفية بالجهاز",
  "Recumbent Bike": "الدراجة المستلقية",
  "Renegade Row (Dumbbell)": "تجديف رينيجيد بالدمبل",
  "Reverse Crunch": "الكرنش العكسي",
  "Reverse Curl (Barbell)": "المرجحة العكسية بالبار",
  "Reverse Curl (Cable)": "المرجحة العكسية بالكابل",
  "Reverse Curl (Dumbbell)": "المرجحة العكسية بالدمبل",
  "Reverse Fly Single Arm (Cable)": "التفتيح العكسي بذراع واحدة بالكابل",
  "Reverse Grip Concentration Curl": "مرجحة التركيز بقبضة عكسية",
  "Reverse Grip Lat Pulldown (Cable)": "سحب الظهر بقبضة عكسية بالكابل",
  "Reverse Grip Triceps Pushdown": "سحب الترايسبس لأسفل بقبضة عكسية",
  "Reverse Hyperextension": "التمديد الخلفي العكسي",
  "Reverse Lunge": "الطعنة الخلفية",
  "Reverse Lunge (Barbell)": "الطعنة الخلفية بالبار",
  "Reverse Lunge (Dumbbell)": "الطعنة الخلفية بالدمبل",
  "Reverse Plank": "البلانك العكسي",
  "Reverse Wrist Curl (Dumbbell)": "ثني المعصم العكسي بالدمبل",
  "Romanian Deadlift (Barbell)": "الرفعة الرومانية بالبار",
  "Romanian Deadlift (Dumbbell)": "الرفعة الرومانية بالدمبل",
  "Romanian Deadlift (Smith Machine)": "الرفعة الرومانية بجهاز سميث",
  "Rope Cable Curl": "مرجحة البايسبس بالحبل على الكابل",
  "Rope Straight Arm Pulldown": "السحب بذراع مستقيمة بالحبل",
  "Running": "الجري",
  "Russian Twist (Bodyweight)": "اللف الروسي بوزن الجسم",
  "Russian Twist (Weighted)": "اللف الروسي بوزن إضافي",
  "Seal Row (Barbell)": "تجديف سيل بالبار",
  "Seal Row (Dumbbell)": "تجديف سيل بالدمبل",
  "Seated Cable Row - Bar Grip": "التجديف بالكابل جالساً بقبضة البار",
  "Seated Cable Row - Bar Wide Grip": "التجديف بالكابل جالساً بقبضة واسعة",
  "Seated Cable Row - V Grip (Cable)": "التجديف بالكابل جالساً بمقبض V",
  "Seated Chest Flys (Cable)": "تفتيح الصدر بالكابل جالساً",
  "Seated Dip Machine": "الغطس بالجهاز جالساً",
  "Seated Incline Curl (Dumbbell)": "مرجحة البايسبس بالدمبل على المقعد المائل",
  "Seated Incline Hammer Curl (Dumbbell)": "مرجحة المطرقة بالدمبل على المقعد المائل",
  "Seated Lateral Raise (Dumbbell)": "الرفرفة الجانبية بالدمبل جالساً",
  "Seated Leg Curl (Machine)": "ثني الرجلين بالجهاز جالساً",
  "Seated Overhead Press (Barbell)": "الضغط العسكري بالبار جالساً",
  "Seated Overhead Press (Dumbbell)": "الضغط العسكري بالدمبل جالساً",
  "Seated Palms Up Wrist Curl": "ثني المعصم والكف للأعلى جالساً",
  "Seated Row (Machine)": "التجديف بالجهاز جالساً",
  "Seated Shoulder Press (Machine)": "ضغط الكتف بالجهاز جالساً",
  "Seated Triceps Press": "ضغط الترايسبس جالساً",
  "Seated Wrist Curl (Barbell)": "ثني المعصم بالبار جالساً",
  "Seated Wrist Extension (Barbell)": "تمديد المعصم بالبار جالساً",
  "Shoulder Press (Dumbbell)": "ضغط الكتف بالدمبل",
  "Shoulder Press (Machine Plates)": "ضغط الكتف بجهاز الأقراص",
  "Shoulder Taps": "لمس الكتفين",
  "Shrug (Barbell)": "هز الكتفين بالبار",
  "Shrug (Cable)": "هز الكتفين بالكابل",
  "Shrug (Dumbbell)": "هز الكتفين بالدمبل",
  "Shrug (Machine)": "هز الكتفين بالجهاز",
  "Shrug (Smith Machine)": "هز الكتفين بجهاز سميث",
  "Side Bend": "الانحناء الجانبي",
  "Side Bend (Dumbbell)": "الانحناء الجانبي بالدمبل",
  "Single Arm Cable Crossover": "تقاطع الكابل بذراع واحدة",
  "Single Arm Cable Row": "التجديف بالكابل بذراع واحدة",
  "Single Arm Curl (Cable)": "مرجحة البايسبس بالكابل بذراع واحدة",
  "Single Arm Landmine Press (Barbell)": "ضغط لاندماين بالبار بذراع واحدة",
  "Single Arm Lat Pulldown": "السحب العلوي بذراع واحدة",
  "Single Arm Lateral Raise (Cable)": "الرفرفة الجانبية بالكابل بذراع واحدة",
  "Single Arm Tricep Extension (Dumbbell)": "تمديد الترايسبس بالدمبل بذراع واحدة",
  "Single Arm Triceps Pushdown (Cable)": "دفع الترايسبس بالكابل بذراع واحدة",
  "Single Leg Extensions": "تمديد الرجلين برجل واحدة",
  "Single Leg Glute Bridge": "جسر المؤخرة برجل واحدة",
  "Single Leg Hip Thrust": "رفع الورك برجل واحدة",
  "Single Leg Hip Thrust (Dumbbell)": "رفع الورك برجل واحدة بالدمبل",
  "Single Leg Press (Machine)": "مكبس الأرجل برجل واحدة بالجهاز",
  "Single Leg Romanian Deadlift (Barbell)": "الرفعة الرومانية برجل واحدة بالبار",
  "Single Leg Romanian Deadlift (Dumbbell)": "الرفعة الرومانية برجل واحدة بالدمبل",
  "Single Leg Standing Calf Raise": "رفع السمانة وقوفاً برجل واحدة",
  "Single Leg Standing Calf Raise (Barbell)": "رفع السمانة وقوفاً برجل واحدة بالبار",
  "Single Leg Standing Calf Raise (Dumbbell)": "رفع السمانة وقوفاً برجل واحدة بالدمبل",
  "Single Leg Standing Calf Raise (Machine)": "رفع السمانة وقوفاً برجل واحدة بالجهاز",
  "Sissy Squat (Weighted)": "قرفصاء سيسي بوزن إضافي",
  "Sit Up": "سيت أب",
  "Sit Up (Weighted)": "سيت أب بوزن إضافي",
  "Skating": "التزلج (سكيتنغ)",
  "Skiing": "التزلج على الثلج",
  "Skullcrusher (Barbell)": "الضغط الفرنسي بالبار",
  "Skullcrusher (Dumbbell)": "الضغط الفرنسي بالدمبل",
  "Sled Pull": "سحب الزلاجة",
  "Snowboarding": "التزلج بلوح الثلج (سنوبورد)",
  "Spider Curl (Barbell)": "مرجحة سبايدر بالبار",
  "Spider Curl (Dumbbell)": "مرجحة سبايدر بالدمبل",
  "Spiderman": "تمرين سبايدرمان",
  "Spinning": "دراجة السبيننغ",
  "Split Jerk": "النتر الخطفي (سبليت جيرك)",
  "Split Squat (Dumbbell)": "قرفصاء سبليت بالدمبل",
  "Squat (Band)": "قرفصاء بالمطاط",
  "Squat (Barbell)": "قرفصاء بالبار",
  "Squat (Bodyweight)": "قرفصاء بوزن الجسم",
  "Squat (Dumbbell)": "قرفصاء بالدمبل",
  "Squat (Machine)": "قرفصاء بالجهاز",
  "Squat (Smith Machine)": "قرفصاء بجهاز سميث",
  "Squat (Suspension)": "قرفصاء بحبال التعليق",
  "Squat Row": "قرفصاء مع تجديف",
  "Stair Machine (Floors)": "جهاز الدرج (طوابق)",
  "Stair Machine (Steps)": "جهاز الدرج (درجات)",
  "Standing Cable Glute Kickbacks": "ركلات خلفية للمؤخرة بالكابل وقوفاً",
  "Standing Calf Raise (Barbell)": "رفع السمانة وقوفاً بالبار",
  "Standing Calf Raise (Dumbbell)": "رفع السمانة وقوفاً بالدمبل",
  "Standing Calf Raise (Machine)": "رفع السمانة وقوفاً بالجهاز",
  "Standing Calf Raise (Smith)": "رفع السمانة وقوفاً بجهاز سميث",
  "Standing Leg Curls": "ثني الرجلين وقوفاً",
  "Standing Military Press (Barbell)": "الضغط العسكري وقوفاً بالبار",
  "Standing Y Raise (Cable)": "رفع Y وقوفاً بالكابل",
  "Step Up": "صعود الصندوق (ستيب أب)",
  "Sternum Pull up (Gironda)": "عقلة القص (جيروندا)",
  "Straight Arm Lat Pulldown (Cable)": "سحب بذراعين مستقيمتين بالكابل",
  "Straight Leg Deadlift": "الرفعة الميتة بأرجل مستقيمة",
  "Stretching": "تمارين الإطالة",
  "Suitcase Carry (Dumbbell)": "حمل الحقيبة بالدمبل",
  "Sumo Squat": "قرفصاء سومو",
  "Sumo Squat (Barbell)": "قرفصاء سومو بالبار",
  "Sumo Squat (Dumbbell)": "قرفصاء سومو بالدمبل",
  "Toe Touch": "لمس أصابع القدمين",
  "Torso Rotation": "تدوير الجذع",
  "Treadmill": "جهاز المشي",
  "Triceps Dip": "ديبس الترايسبس",
  "Triceps Dip (Assisted)": "ديبس الترايسبس بالمساعدة",
  "Triceps Dip (Weighted)": "ديبس الترايسبس بوزن إضافي",
  "Triceps Extension (Barbell)": "تمديد الترايسبس بالبار",
  "Triceps Extension (Cable)": "تمديد الترايسبس بالكابل",
  "Triceps Extension (Dumbbell)": "تمديد الترايسبس بالدمبل",
  "Triceps Extension (Machine)": "تمديد الترايسبس بالجهاز",
  "Triceps Extension (Suspension)": "تمديد الترايسبس بحبال التعليق",
  "Triceps Kickback (Cable)": "ركلة الترايسبس الخلفية بالكابل",
  "Triceps Kickback (Dumbbell)": "ركلة الترايسبس الخلفية بالدمبل",
  "Triceps Pressdown": "دفع الترايسبس لأسفل",
  "Triceps Rope Pushdown": "دفع الترايسبس لأسفل بالحبل",
  "Upright Row (Barbell)": "تجديف عمودي بالبار",
  "Upright Row (Cable)": "تجديف عمودي بالكابل",
  "Upright Row (Dumbbell)": "تجديف عمودي بالدمبل",
  "V Up": "تمرين V للبطن",
  "Vertical Traction (Machine)": "سحب عمودي بالجهاز",
  "Waiter Curl (Dumbbell)": "مرجحة النادل بالدمبل",
  "Walking": "مشي",
  "Walking Lunge (Dumbbell)": "طعنات مشي بالدمبل",
  "Walking Lunge (Sandbag)": "طعنات مشي بكيس الرمل",
  "Wall Ball": "رمي الكرة على الحائط",
  "Warm Up": "إحماء",
  "Wide Pull Up": "عقلة بقبضة واسعة",
  "Wide-Elbow Triceps Press (Dumbbell)": "ضغط الترايسبس بمرفقين متباعدين بالدمبل",
  "Wrist Roller": "بكرة المعصم",
  "Yoga": "يوغا",
  "Zercher Squat": "قرفصاء زيرشر",
  "Zottman Curl (Dumbbell)": "مرجحة زوتمان بالدمبل",
};
